In [1]:
import numpy as np

In [24]:
l = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
n = np.array(l)
n.ndim, n.shape, n.size, n.dtype.name, n.itemsize, n.data

(2, (3, 3), 9, 'int32', 4, <memory at 0x00000260F94F28B8>)

In [27]:
n = np.arange(15).reshape(3, 5)
n.ndim, n.shape, n.size, n.dtype.name, n.itemsize, n.data

(1, (15,), 15, 'int32', 4, <memory at 0x00000260F82F6F48>)

In [54]:
np.arange(1500000000).size

1500000000

In [62]:
a = np.array([(1.5, 2, 3), (4, 5, 6)])
print(a)
print("="*40)
b = np.array(((1.5, 2, 3), (4, 5, 6)))
print(b)
print("="*40)
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [77]:
print(np.zeros((3, 4)))
print("="*40)
print(np.ones((2, 3, 4), dtype=np.int16))
print("="*40)
print(np.empty((2, 3)))
print("="*40)
print(np.arange(10, 30, 5))
print("="*40)
print(np.arange(0, 2, 0.3))  # it accepts float arguments

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [80]:
from numpy import pi

print(np.linspace(0, 2, 9))  # 9 numbers from 0 to 2
print("="*40)
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
print(x)
print("="*40)
f = np.sin(x)
print(f)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.394

In [82]:
a = np.arange(6)                    # 1d array
print(a)
print("="*40)
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)
print("="*40)
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
